# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

minecraft_version=26.2

# Fabric Properties
fabric_loader_minimum=0.18.4
fabric_loader_version=0.19.3
fabric_api_version=0.157.0+26.2

# Mod Properties
mod_version = 1.5.10
maven_group = com.gmail.sneakdevs.diamondeconomy
archives_base_name = diamondeconomy

# Dependencies
cloth_config_version=26.2.155
placeholder_api_version=3.1.0-beta.1+26.2
sqlite_version=3.53.2.1
common_economy_api=2.0.0